### ISSUE TITLE
Landing pages

### ISSUE THREAD

**Issue by Hillcrest01** [JoyMaryK/jenga#1]
Hi JoyMary, what a nice project this is. However, the landing pages are not working.

**Comment by JoyMaryK** [comment]
Hi @Hillcrest01 , thanks for letting me know! Would you like to collaborate on fixing it?

**Comment by Hillcrest01** [comment]
Yeah sure, I would like to.

**Comment by Hillcrest01** [comment]
Hello, was a little bit held up but I will start working on it soon

**Comment by JoyMaryK** [comment]
Hi @Hillcrest01, no worries! I have added you as a collaborator so feel free to contribute whenever. 
Thanks!

**Comment by Hillcrest01** [comment]
Thank you @JoyMaryK
